#!/usr/bin/env node

const interact = require('./lib/index.js')

const config = {}

config.imports = { fs: 'fs' }
config.historyFile = '.node_repl_history'
config.historyLength = 100
config.capturePromises = true
config.useColors = true
config.requirePrefix = '' // if using a different node_modules folder
config.waitPromises = 500
config.prompt = '> '

// config.postloads = [ context => console.log('\r1|5. postload') ]
// config.inits = [ context => console.log('\r2. init') ]
// config.persists = [ { get: context => console.log('\r3. persist get'), set: (context, value) => console.log('\r6. persist set') } ]
// config.preloads = [ context => console.log('\r4. preload') ]

interact.start(config)
